#!/usr/bin/env sh

# bar settings {{{
yabai -m config status_bar                   on
yabai -m config status_bar_text_font         "Operator Mono Nerd Font:Bold:12.0"
yabai -m config status_bar_icon_font         "Font Awesome 5 Pro:Regular:12.0"
yabai -m config status_bar_background_color  0xe0202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip          
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        
# }}}
# global settings {{{
# general space settings {{{
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
# }}}
# general window settings {{{
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config window_shadow                off
yabai -m config window_border                on
yabai -m config window_border_width          4
yabai -m config window_border_placement      interior
yabai -m config window_border_radius         1.0
yabai -m config active_window_border_topmost off
yabai -m config window_gap                   5
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config normal_window_border_color   0xff505050
yabai -m config active_window_border_color   0xff775759
yabai -m config insert_window_border_color   0xffd75f5f
# }}}
# mouse settings {{{
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autoraise
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
# }}}


# rules {{{
# yabai behavior towards applications
yabai -m rule --add app="^Digital Colou?r Meter$" manage=off border=off topmost=on sticky=on
yabai -m rule --add app="Messages" manage=off topmost=on
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off border=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add title='.*Preferences.*' manage=off border=off topmost=on
yabai -m rule --add title='.*Install.*' manage=off border=off topmost=on
yabai -m rule --add app="System Preferences" app="^System Predereneces$" border=off topmost=on
yabai -m rule --add app="Activity Monitor" manage=off border=off
yabai -m rule --add app="Calculator" manage=off border=off
yabai -m rule --add app="Transmission" manage=off border=off
yabai -m rule --add app="Dictionary" manage=off border=off
yabai -m rule --add app="Preview" manage=off border=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="General windows" title="General" manage=float
# signals
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
# }}}
echo "yabai configuration loaded.."
