#!/usr/bin/env sh

# global settings {{{
# general space settings {{{
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
# }}}
# general window settings {{{
yabai -m config window_placement             first_child
yabai -m config window_topmost               on
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.8
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.95
yabai -m config window_shadow                float
yabai -m config window_gap                   5
yabai -m config split_ratio                  0.38
yabai -m config auto_balance                 on
# }}}
# mouse settings {{{
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autoraise
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
# }}}


# rules {{{
# yabai behavior towards applications
#	yabai -m rule --add app="^Digital Colou?r Meter$" manage=off sticky=on
#	yabai -m rule --add app="Messages" manage=off
#	yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
#	yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
#	yabai -m rule --add title='.*Preferences.*' manage=off
#	yabai -m rule --add title='.*Install.*' manage=off
#	yabai -m rule --add app="System Preferences" app="^System Prefereneces$"
#	yabai -m rule --add app="Activity Monitor" manage=off
#	yabai -m rule --add app="Calculator" manage=off
#	yabai -m rule --add app="Transmission" manage=off
#	yabai -m rule --add app="Dictionary" manage=off
#	yabai -m rule --add app="Preview" manage=off
#	yabai -m rule --add label="App Store" app="^App Store$" manage=off
#	yabai -m rule --add label="General windows" title="General" manage=off
# signals
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
# }}}
echo "yabai configuration loaded.."
